[details]
name = "Splat"
logging = true
shape = { select = "Random", steps  = 64, parallel = 1 }


[[job]]
cmd = "ls"
stdout = "/tmp/ls.out"
value = 50

[[job]]
cmd = "pwd"
stderr = "/tmp/pwd.err"
value = 50
